# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Bstack'
- script: |
    echo Starting the build
    mvn clean
    mvn compile
    mvn test -P parallel
  displayName: 'Build with Maven'
- task: BrowserStackResults@0